package com.miaosha.dao;

import com.miaosha.dataobject.UserDO;

public interface UserDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Mon Mar 23 11:52:44 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Mon Mar 23 11:52:44 CST 2020
     */
    int insert(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Mon Mar 23 11:52:44 CST 2020
     */
    int insertSelective(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Mon Mar 23 11:52:44 CST 2020
     */
    UserDO selectByPrimaryKey(Integer id);

    /**
     * 通过手机号码查找用户信息，用于登陆验证
     * @param telPhone
     * @return
     */
    UserDO selectByTelPhone(String telPhone);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Mon Mar 23 11:52:44 CST 2020
     */
    int updateByPrimaryKeySelective(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Mon Mar 23 11:52:44 CST 2020
     */
    int updateByPrimaryKey(UserDO record);
}